name: Hello Github Actions 
  
on: push


jobs: 
  greet:
    runs-on: ubuntu-latest


    steps:
      -name: Checkout code 
       uses: actions/checkout@v5

      -name: Say Hello
       run: echo "Hello From GitHub Actions! Day 40"

       -name: Show Date and time 
       run: date

       -name: Show branch name 
       run: echo "Branch: ${{ github.ref_name }}"

       -name: list repository files 
       run: ls -la

       -name: Show operating system
       run: uname -a 


       -name: Intentional failure
        run: exit 1
