name: Day 44 - Secrets

on:
  workflow_dispatch:

jobs:
  secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret is set
        env:
          MY_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          if [ -n "$MY_MESSAGE" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi